[package]
name = "libertas-weather"
version = "0.1.0"
edition = "2024"
description = "Application-tailored, versioned weather data definitions for Libertas"

[dependencies]
libertas = { path = "../../../rust/libertas-rs/crates/libertas", package = "libertas" }
libertas_macros = { path = "../../../rust/libertas-rs/crates/libertas_macros", package = "libertas_macros" }

[lib]
name = "libertas_weather"
crate-type = ["rlib"]
