[package]
name = "libertas-weather"
version = "0.1.0"
edition = "2024"
description = "Application-tailored, versioned weather data definitions for Libertas"

[dependencies]
libertas = { git = "https://github.com/LibertasIoT/libertas-rs.git", branch = "main", package = "libertas" }
libertas_macros = { git = "https://github.com/LibertasIoT/libertas-rs.git", branch = "main", package = "libertas_macros" }

[lib]
name = "libertas_weather"
crate-type = ["rlib"]
