[package]
name = "libertas-tax"
version = "0.1.0"
edition = "2024"
description = "U.S. federal tax year 2026 tax return prototype"

[dependencies]
libertas = { path = "../../../rust/libertas-rs/crates/libertas", package = "libertas" }
libertas_macros = { path = "../../../rust/libertas-rs/crates/libertas_macros", package = "libertas_macros" }

[lib]
name = "libertas_tax"
crate-type = ["rlib"]
