[package]
name = "libertas-sprinkler_agent"
version = "0.1.0"
edition = "2024"

[dependencies]
libertas = { path = "../../../rust/libertas-rs/crates/libertas", package = "libertas" }
libertas-hub = { path = "../../../rust/libertas-rs/crates/libertas-hub", package = "libertas-hub" }
libertas_macros = { path = "../../../rust/libertas-rs/crates/libertas_macros", package = "libertas_macros" }
libertas-matter = { path = "../../../rust/libertas-matter/libertas-matter", package = "libertas-matter", default-features = false, features = ["alloc"] }
libertas-weather = { path = "../libertas-weather", package = "libertas-weather" }
libm = "0.2.16"

[lib]
name = "libertas_sprinkler_agent"
crate-type = ["rlib"]
