[package]
name = "libertas-types"
version = "0.1.0"
edition = "2024"
description = "Shared schema-only Libertas sample types"

[dependencies]
libertas = { git = "https://github.com/LibertasIoT/libertas-rs.git", branch = "main", package = "libertas" }
libertas_macros = { git = "https://github.com/LibertasIoT/libertas-rs.git", branch = "main", package = "libertas_macros" }

[lib]
name = "libertas_types"
crate-type = ["rlib"]
