[package]
name = "libertas-virtual_irrigation_control"
version = "0.1.0"
edition = "2024"

[dependencies]
libertas = { git = "https://github.com/LibertasIoT/libertas-rs.git", package="libertas" }
libertas_macros = { git = "https://github.com/LibertasIoT/libertas-rs.git", package="libertas_macros" }
libertas-matter = { git = "https://github.com/LibertasIoT/libertas-matter", default-features = false, features = ["alloc"] }

[lib]
name = "libertas_virtual_irrigation_control"
crate-type = ["rlib"]
